---
- hosts: proxmox
  become: true
  tasks:
    - name: Update APT package index
      apt:
        update_cache: yes

    - name: Upgrade all packages to the latest version
      apt:
        upgrade: dist

    - name: Clean up unused dependencies
      apt:
        autoremove: yes
        autoclean: yes
